sudo: false

language: python

python:
   - "3.6"

env:
    - NODE_VERSION="0.12"

before_install:
    - cat .travis.yml
    - pip install --upgrade pip
    - pip --version
    - nvm install $NODE_VERSION

install:
    - pip install autopep8
    - pip install coverage
    - pip install mypy
    - pip install pylint
    - pip install numpy
    - pip install flask
    - pip install request
    - pip install requests
    - pip list
    - npm install newman


before_script:
    - date
    - uname -a
    - printenv | sort
    - autopep8  --version
    - coverage  --version
    - git       --version
    - make      --version
    - mypy      --version
    - pydoc     --version
    - pylint    --version
    - python3.6 --version
    - ls -al
    - cat makefile

script:
    - make travis
    - tests/node_modules/.bin/newman run tests/bitcoinz.postman_collection.json
