sudo: false

matrix:
  include:
    language: python

    python: 3.6

    before_install:
        - cat .travis.yml

    install:
        - pip install --upgrade pip
        - pip --version
        - pip install autopep8
        - pip install coverage
        - pip install mypy
        - pip install pylint
        - pip install numpy
        - pip install flask
        - pip install request
        - pip install requests
        - pip list


    before_script:
        - date
        - uname -a
        - printenv | sort
        - autopep8  --version
        - coverage  --version
        - git       --version
        - make      --version
        - mypy      --version
        - pydoc     --version
        - pylint    --version
        - python3.6 --version
        - ls -al
        - cat makefile

    script:
        - make travis

    language: node_js

    node_js:
        - "8.2.1"
    install:
        - npm install newman
    before_script:
        - node --version
        - npm --version
        - node_modules/.bin/newman --version
    script:
        - node_modules/.bin/newman run tests/bitcoinz.postman_collection.json
