branch-defaults:
  default:
    environment: major
    group_suffix: null
environment-defaults:
  major:
    branch: null
    repository: null
global:
  application_name: major
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: group
  repository: null
  sc: null
  workspace_type: Application
